### PR TITLE
bundles: Add UAI 2023

### PR DESCRIPTION
**Pull request by braun-steven**
Adds the uai2023 bundle, test cases and documentation update.

### CODE REVIEW

**Comment by braun-steven** [comment]
I measured the `base_width_pt` values with `\the\linewidth` for `column=half` and `\the\textwidth` for `column=full` -- I'm not sure if this is the correct way to do it.

**Comment by braun-steven** [comment]
Mh, not sure why the docs ci failed: https://github.com/pnkraemer/tueplots/actions/runs/4022827585/jobs/6912977827#step:4:115 Do you have an idea?

**Review by pnkraemer — COMMENTED** [review]
That looks great, thanks! I appreciate you fixing tox as well :)

Regarding your question:

> I measured the base_width_pt values with \the\linewidth for column=half and \the\textwidth for column=full -- I'm not sure if this is the correct way to do it.

This is one option, and we've certainly done it this way for a couple of templates. Whenever an official call for papers with submission instructions is available (![https://www.auai.org/uai2022/submission_instructions]), I tend to look directly at the template. 

For UAI2023 (in the .cls file) it says 
```
    \geometry{
        % A4 width and Letter height: prints without scaling on both
        a4paper,
        paperheight=11in,
        % mimic Morgan Kaufmann two column style
        textheight=9.25in,
        textwidth=6.75in,
        columnsep=0.25in,
        nohead, % foot kept for page numbers/notice
        footnotesep=9pt plus 4pt minus 2pt,
        % center vertically and horizontally
        % (was asymmetric in the past, outdated with electronic proceedings)
        centering
    }
```
so I guess the width is 6.75 inches for full-width and 3.75 for half-width. If you like, you can keep it the way it is or use `_from_base_in` instead of `_from_base_pt`. Your call :)

**Comment by braun-steven** [comment]
Thanks, let's go with inches! Before I update this, how did you come up with 3.75 for half-width? Shouldn't this be 3.25 instead, i.e. `(textwidth - columnsep / 2) = 3.25`?

**Comment by pnkraemer** [comment]
> how did you come up with 3.75 for half-width

I don't know either; you're of course right...

**Review by pnkraemer — APPROVED** [review]

**Pull request merged**
