### PR TITLE
Add list of supported venues to README and docs

### PR DESCRIPTION
**Pull request by steven-lang**
First time users might be interested in a quick overview of whether their targeted venue is supported by tueplots. While this information can be found in the [API docs](https://tueplots.readthedocs.io/en/latest/docs_api/tueplots.bundles.html), I think it would be good to provide an overview on the "landing page" of this package, i.e., either the GitHub README file or the docs index file.

### CODE REVIEW

**Comment by pnkraemer** [comment]
I think this is a great idea, thank you for taking the initiative! 

I am wondering whether the proposed implementation is the best solution, though, because it makes the addition of future styles more complex: whenever a new set of styles is implemented, say for TMLR, it would have to be added manually to both files. I would suppose such lists might get outdated quickly.

So instead, how about we have a loose bullet point list of supported venues (without years, just the name of the venue) in the README and add a link to the API docs somewhere close to the list? This way, it would be easy to see which kind of venue is supported, but we would not add overhead to future contributions. 

What do you think?

**Comment by steven-lang** [comment]
Totally agree with you, I've updated the PR with your suggestion: a simple list of supported venues and a link to the API for further details.

**Review by pnkraemer — COMMENTED** [review]
Thanks a lot for the quick update! :) 

One last thing before merging:
I think I would prefer if the list of venues was only included in _either_ the README or the index. Otherwise, it seems a bit duplicated. (And again, the lists might diverge in the future unless we work hard on keeping them identical, which I would like to avoid :)).

I would personally favour the README. What do you think? 

Other than that, good to go!

**Comment by steven-lang** [comment]
I guess that's up to you: where do you want new users to land first? The readthedocs site or rather the GitHub repo? If you were to share a single link to your project now, which one would it be? :-)

**Comment by pnkraemer** [comment]
Good point. Let's go for the index. Thanks for following up!

**Review by pnkraemer — APPROVED** [review]
Thank you!

**Pull request merged**
